---
- name: Install and configure web stack
  hosts: all
  become: true
  
  tasks:
  
  - name: Install Nginx
    apt:
      name: nginx
      state: present
  
  - name: Start Nginx
    service:
      name: nginx
      state: started
      
  - name: Install MySQL
    apt:
      name: mysql-server
      state: present

  - name: Start mysql
    service:
      name: mysql
      state: started    

  - name: Install PostgreSQL
    apt:
      name: postgresql
      state: present

  - name: start postgresql
    service:
      name: postgresql
      state: started      
      


  - name: Install Git
    apt:
      name: git
      state: present
      
      
  
      

      

      
